apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv-nfs-elasticsearch
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/persistent/elasticsearch
    server: 10.1.10.15
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
spec:
  storageClassName: pv-nfs-elasticsearch
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
