apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: kube-logging
spec:
  rules:
  - host: kibana.home.virtualelephant.com
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 5601
