apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-elastic
  namespace: kube-logging
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/persistent/kibana
    server: 10.1.10.15
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana
  namespace: kube-logging
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
